### ISSUE TITLE
Request for cebuano localization translation

### ISSUE THREAD

**Issue by rfece143** [ancap-ch/from-en#1038]
Good day!

Hi, I want to ask your permission to allow me to contribute in translating this project in our local language which is "Visayan Language". This language is my mother toque.

I hope you consider my intention.

Thanks and Godbless!

**Comment by swfsql** [comment]
Hello rfece, I'm sorry for the delay in responding.
Due to the high frequency of people using bots to translate text, the collaborators were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

I believe we'd have a slow procedure for Visayan since you'd be the first translator for this language!
(we'd need to slowly build up a dependence on your work as translator/proofreader, which is not a simple process, unfortunately)

I thank you for trying to find the best way to contribute, and I'm sorry I took so long to reply.
So.. since this project is not involved with utopian anymore, then I'll be closing this issue for now.
