### ISSUE TITLE
Cebuano Translation Request

### ISSUE THREAD

**Issue by sageyuan** [ancap-ch/from-en#1399]
Hello Good day Sir!
i would like to request a translation string. English to Cebuano Translation. I am a native speaker of cebuano language.

**Comment by swfsql** [comment]
Hello sageyuan, I'm sorry for the delay in responding.
Due to the high frequency of people using bots to translate text, the collaborators (including those specifically for the cebuano case) were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

I thank you for trying to find the best way to contribute, and I'm sorry I took so long to reply.
So.. since this project is not involved with utopian anymore, then I'll be closing this issue for now.
