### ISSUE TITLE
Requesting for translation from English language to Filipino language

### ISSUE THREAD

**Issue by garry19** [ancap-ch/from-en#1400]
I am Garry Obina requesting your permission to allow me to translate your prestigious project from English to Filipino Language, which would be very beneficial for Filipinos as future users. Thank you and have a good day.

**Comment by swfsql** [comment]
Hello Garry, I'm sorry for the delay in responding.
Due to the high frequency of people using bots to translate text, the collaborators (those specifically for the filipino case) were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

I thank you for trying to find the best way to contribute, and I'm sorry I took so long to reply.
So.. since this project is not involved with utopian anymore, then I'll be closing this issue for now.
