### ISSUE TITLE
May I help in the Tagalog or Cebuano Translations?

### ISSUE THREAD

**Issue by caratzky** [ancap-ch/from-en#1586]
Good Day, @romero350 and other concerned authorities for this project,

I've noticed there are a lot of untranslated files yet in the tl (Tagalog) and ceb (Cebuano) folders. I would like to know if I can help? - So that the translations will be completed faster. I am a natural born Cebuano and is well-experienced in Tagalog Translations. I hope you'll accept my application/request for collaboration. Thank you.

Best Regards,
caratzky | Rizalino Caratao

**Comment by swfsql** [comment]
Hello caratzky, I'm sorry for the delay in responding.
Due to the high frequency of people using bots to translate text, the collaborators (including romero or others, specifically for the cebuano/tagalog case) were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

I thank you for trying to find the best way to contribute, and I'm sorry I took so long to reply.
So.. since this project is not involved with utopian anymore, then I'll be closing this issue for now.
