### ISSUE TITLE
Basic Steps of System for Translation / NEED HELP FOR STEPS OF TRANSLATION IN GITHUB

### ISSUE THREAD

**Issue by altandoyran** [ancap-ch/from-en#1617]
I would like to translate texts in Turkish. But the problem is I not familiar with GitHub system. If there is any kind of guide or how to structure I would be so glad to see it. If possible please help me to start this process. What I have to do first? Second ….. How should I get text to for translation? How should I make them checked? What should I do to merge them? …..

**Thank you in advance.**

**Comment by swfsql** [comment]
Hello altandoyran, I'm sorry for the delay in responding.

We've been trying to setup some guidance, but we couldn't quite put our stuff together.
Overall, I was expecting that people would annotate that they would be translating a particular file (since we started having multiple people trying to translate the same text - and that was utter confusing for everyone involved) but people were not using this "system" (for sure, because it is not intuitive).

Nowadays, I understand that all PR (contributions that want to be merged) should point to a previously created issue). So the best system would be to require the author to create a issue before starting the contributions, and that issue's acceptance would need to cause annotations in some document so others can know what text is free to be worked on.

I thank you for trying to find the best way to contribute, and I'm sorry I took so long to reply.
So.. since this project is not involved with utopian anymore, then I'll be closing this issue for now.
