### ISSUE TITLE
Cebuano Translation Request

### ISSUE THREAD

**Issue by rushy13** [ancap-ch/from-en#1656]
Hello! 
It so awesome to be on this platform! 
Having said so, I would like to express my interest in translating the Cebuano texts to English. I'm a native Cebuano from the southern Philippines and now studying in Korea. This project is a great diversion for me while making a contribution. I have translated 1209 words on this portion.
https://github.com/ancap-ch/from-en/pull/1633/commits/23613907e958b3865df7d33329c1833e48a86e23

Please consider my request.
Thank you!
Rushie

**Comment by swfsql** [comment]
Hello rushy, I'm sorry for the delay in responding.
Due to the high frequency of people using bots to translate text, the collaborators were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

When I have time and the means to it, I'll try to re-open the issue and analyze your PR (I apologize if it won't be meaningful reward-wise for you by now). So I'll be closing this issue for now.
