### ISSUE TITLE
I am interested in several files and look forward to get the translation permission 

### ISSUE THREAD

**Issue by nicealler** [ancap-ch/from-en#1858]
Hello, I am interested in several of the documents and I would like to contribute my translation. My goal is to work hard on getting these words translated. I would like to ask, if you could please merge my PR (#1816 ), thank you very much!

**Comment by swfsql** [comment]
Hello nicealler, I'm sorry for the delay in responding.
Due to the high frequency of people using bots to translate text, the collaborators were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

When I have time and the means to it, I'll try to re-open the issue and analyze your PR (I apologize if it won't be meaningful reward-wise for you by now). So I'll be closing this issue for now.
