### ISSUE TITLE
may i joinTranslate to Indonesia

### ISSUE THREAD

**Issue by aldianrony1** [ancap-ch/from-en#576]
hi may i join to help your project to translate to indonesian (ID)

**Comment by swfsql** [comment]
Sorry for taking this long to reply you, aldianrony..
on my part, I'm trying to organize some aspects of the contributions, it may take a while until we are able coordinate with more members

**Comment by swfsql** [comment]
Hello aldianrony, I'm sorry for the delay in responding.
Due to the high frequency of people using bots to translate text, the collaborators were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

I thank you for trying to find the best way to contribute, and I'm sorry I took so long to reply.
So.. since this project is not involved with utopian anymore, then I'll be closing this issue for now.
