### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by kookjames** [ancap-ch/from-en#664]
can anyone tell me how can i contribute in Urdu language translation? I am much confused how can i commit and also don't know how to send pull request please help. Thanks

**Comment by swfsql** [comment]
Hello kookjames, I'm sorry for the delay in responding.

We've been trying to setup some guidance, but we couldn't quite put our stuff together.
Overall, I was expecting that people would annotate that they would be translating a particular file (since we started having multiple people trying to translate the same text - and that was utter confusing for everyone involved) but people were not using this "system" (for sure, because it is not intuitive).

Nowadays, I understand that all PR (contributions that want to be merged) should point to a previously created issue). So the best system would be to require the author to create a issue before starting the contributions, and that issue's acceptance would need to cause annotations in some document so others can know what text is free to be worked on.

Due to the high frequency of people using bots to translate text, the collaborators were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

We were working towards having collaborators who would review Urdu translations (which was unfortunately a slow process, in part for my cause due to misunderstandings), and i thank you for trying to find the best way to contribute, and I'm sorry I took so long to reply.
But now this project is not involved with utopian anymore,
then I'll be closing this issue for now.
