### ISSUE TITLE
request to translate into Indonesian

### ISSUE THREAD

**Issue by mohdhaekal** [ancap-ch/from-en#679]
hello sir ... may i translate into indonesian language.for Indonesian people to read it easier ..... thank you

**Comment by nasrullahilyas** [comment]
hai, may i translate this projek?

**Comment by swfsql** [comment]
Hello mohdhaekal and nasrullahilyas,
I'm sorry for the delay in responding.

Due to the high frequency of people using bots to translate text, the collaborators were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

I thank you for trying to find the best way to contribute, and I'm sorry I took so long to reply.
So.. since this project is not involved with utopian anymore, then I'll be closing this issue for now.
