### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by halokaya67** [ancap-ch/from-en#686]
I want to help this project by translating it into turkish. I'm turkish and 25 years old. I'm working as an english teacher in a school. I think i can help. Please just show me which file should i translate and you will see. You won't regret because i take my job serious.

**Comment by yunuskalkan** [comment]
Ben de bu işe yeni bşladım, daha doğrusu başlamaya çalışıyorum. nereden başlayacağımı, ne yapacağımı ben de pek bilmiyorum. Bu konuda bana da yardımcı olabilir misin?

**Comment by altandoyran** [comment]
Merhaba bende yeni başladım Github üzerinden çeviri yapmaya. Çeviriler esnasında adım adım ne yapılmalı yani metnin belirlenmesi tercümenin yapılması ve sisteme yüklenmesi ... gibi süreçlerde nasıl bir yol izlemeliyiz? Konu hakkında yardımcı olabilirsen çok sevinirim.

**Comment by swfsql** [comment]
Hello halokaya, yunuskalkan and altandoryan, I'm sorry for the delay in responding.
Due to the high frequency of people using bots to translate text, the collaborators were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

I thank you guys for trying to find the best way to contribute, and I'm sorry I took so long to reply.
So.. since this project is not involved with utopian anymore, then I'll be closing this issue for now.
