### ISSUE TITLE
Translation into Filipino

### ISSUE THREAD

**Issue by agentzero1** [ancap-ch/from-en#777]
Good day,

 Can I translate it to my native languge which is Fililino ?

**Comment by swfsql** [comment]
Hello agent zero, I'm sorry for the delay in responding.
Due to the high frequency of people using bots to translate text, the collaborators (including romero or others, specifically for the cebuano/tagalog case) were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

I thank you for trying to find the best way to contribute, and I'm sorry I took so long to reply.
So.. since this project is not involved with utopian anymore, then I'll be closing this issue for now.
