### ISSUE TITLE
Requesting for translation from English language to Filipino language.

### ISSUE THREAD

**Issue by calmabryan27ree** [ancap-ch/from-en#846]
To Whom It May Concern

I am Bryan Calma would like to ask for permission to allow me to translate your prestigious project from English to Filipino  language for the benefits of Filipino individuals whom a future users.

Thank you

Respectfully Yours,
Bryan Calma

**Comment by swfsql** [comment]
Hello calmabryan, I'm sorry for the delay in responding.
Due to the high frequency of people using bots to translate text, the collaborators (including romero or others, specifically for the cebuano/tagalog case) were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

I thank you for trying to find the best way to contribute, and I'm sorry I took so long to reply.
So.. since this project is not involved with utopian anymore, then I'll be closing this issue for now.
